### ISSUE TITLE
加入`频道`的信息`Event`

### ISSUE THREAD

**Issue by SlieFamily** [SlieFamily/ErikaBot#9]
来源：[nonebot2频道补丁](https://gist.github.com/mnixry/57033047be55956e2168284bcf0bd4b6)
- [x] 为频道专门设立`handle()`
- [x] 转移推特消息推送

**Comment by EPKFG** [comment]
频道能分子频道加入推送不（就是子频道当一个群，然后不同子频道关注不一样的人这样）

**Comment by EPKFG** [comment]
来源已更新：https://github.com/mnixry/nonebot-plugin-guild-patch
